# -*- coding: utf-8 -*-
"""Well_tarefapratica_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VNC0OozLgRF_SdgvxOpxbHxhfQmW-7gs
"""

while True:
  nome = input("Qual é o seu nome?")
  if nome == "0":
    break
  pronome = input("Qual pronome você usa?")
  if pronome == "0":
    break
  idade = input("Qual é a sua idade?")
  if idade == "0":
    break
  email = input("Qual é o seu email?")
  if email == "0":
    break
  cidade = input("Qual é a cidade você mora?")
  if cidade == "0":
    break

  print("\nDados cadastrados:")

  print(f"nome: {nome} \npronome: {pronome} \nidade: {idade} \nemail: {email} \ncidade: {cidade}")


  opcao = input("\nDesejar continuar? (s/n)")

  if opcao.lower() == "n":
    print("Adeus")
    break